# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar 
$applauncher = wofi
$terminal = alacritty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
$save-area = grimblast save area "$(zenity --file-selection --save --confirm-overwrite --filename=$HOME/Pictures/screenshots/screenshot.png)"
$save-area = grimblast save area "$(zenity --file-selection --save --confirm-overwrite --filename=$HOME/university/f25/screenshot.png)"

