# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

monitor = , preferred, auto-up, 1


# If you need to scale things like steam etc, please uncomment these lines.
xwayland {
  force_zero_scaling = true       # Unscale XWayland
}

# Adjust GDK_SCALE accordingly to your liking.
#env = GDK_SCALE, 1.25                   # GDK Scaling Factor


# At home setup 

# Middle / Main monitor
monitorv2 {
  output = desc:Dell Inc. DELL U2722D DHHTDH3
  mode = 2560x1440@59.95
  position = 0x0
  scale = 1
  transform = 0
}

# Right side monitor
monitorv2 {
  output = desc:Dell Inc. DELL P2723DE CJHP1L3
  mode = 2560x1440@59.95
  position = 2560x0
  scale = 1
  transform = 0
}

# Laptop monitor
monitorv2 {
  output = desc:Lenovo Group Limited 0x403D
  disabled = false
  mode = 1920x1200@60.00
  position = auto
  scale = 1
  transform = 0
}
